#include "get_next_line.h"
#include <stdio.h>
int	main(void)
{
	int test;
	test = open("filetest2.txt", O_RDONLY);
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
	printf("o/:%s", get_next_line(test));
}
